export const flagsByLang: Record<string, string> = {
  aa: "🇩🇯", // Afar (Djibouti)
  ab: "🇬🇪", // Abjasio
  af: "🇿🇦", // Afrikaans
  am: "🇪🇹", // Amárico
  ar: "🇸🇦", // Árabe
  as: "🇮🇳", // Asamés
  ay: "🇧🇴", // Aimara
  az: "🇦🇿", // Azerí
  ba: "🇷🇺", // Bashkir
  be: "🇧🇾", // Bielorruso
  bg: "🇧🇬", // Búlgaro
  bh: "🇮🇳", // Bhoypurí
  bi: "🇻🇺", // Bislama
  bn: "🇧🇩", // Bengalí
  bo: "🇨🇳", // Tibetano
  br: "🇫🇷", // Bretón
  bs: "🇧🇦", // Bosnio
  ca: "🇪🇸", // Catalán
  co: "🇫🇷", // Corso
  cs: "🇨🇿", // Checo
  cy: "🏴", // Galés
  da: "🇩🇰", // Danés
  de: "🇩🇪", // Alemán
  dz: "🇧🇹", // Dzongkha
  el: "🇬🇷", // Griego
  en: "🇬🇧", // Inglés
  eo: "🌍", // Esperanto
  es: "🇪🇸", // Español
  et: "🇪🇪", // Estonio
  eu: "🇪🇸", // Vasco
  fa: "🇮🇷", // Persa
  fi: "🇫🇮", // Finés
  fj: "🇫🇯", // Fiyiano
  fo: "🇫🇴", // Feroés
  fr: "🇫🇷", // Francés
  fy: "🇳🇱", // Frisón
  ga: "🇮🇪", // Irlandés
  gd: "🏴", // Gaélico escocés
  gl: "🇪🇸", // Gallego
  gn: "🇵🇾", // Guaraní
  gu: "🇮🇳", // Guyaratí
  ha: "🇳🇬", // Hausa
  he: "🇮🇱", // Hebreo
  hi: "🇮🇳", // Hindi
  hr: "🇭🇷", // Croata
  hu: "🇭🇺", // Húngaro
  hy: "🇦🇲", // Armenio
  id: "🇮🇩", // Indonesio
  is: "🇮🇸", // Islandés
  it: "🇮🇹", // Italiano
  ja: "🇯🇵", // Japonés
  jv: "🇮🇩", // Javanés
  ka: "🇬🇪", // Georgiano
  kk: "🇰🇿", // Kazajo
  km: "🇰🇭", // Jemer
  kn: "🇮🇳", // Canarés
  ko: "🇰🇷", // Coreano
  ku: "🇮🇶", // Kurdo
  ky: "🇰🇬", // Kirguís
  la: "🏛️", // Latín
  ln: "🇨🇩", // Lingala
  lo: "🇱🇦", // Lao
  lt: "🇱🇹", // Lituano
  lv: "🇱🇻", // Letón
  mg: "🇲🇬", // Malgache
  mi: "🇳🇿", // Maori
  mk: "🇲🇰", // Macedonio
  ml: "🇮🇳", // Malayalam
  mn: "🇲🇳", // Mongol
  mo: "🇲🇩", // Moldavo
  mr: "🇮🇳", // Maratí
  ms: "🇲🇾", // Malayo
  mt: "🇲🇹", // Maltés
  my: "🇲🇲", // Birmano
  nb: "🇳🇴", // Noruego Bokmål
  ne: "🇳🇵", // Nepalí
  nl: "🇳🇱", // Neerlandés
  nn: "🇳🇴", // Noruego Nynorsk
  no: "🇳🇴", // Noruego
  oc: "🇫🇷", // Occitano
  or: "🇮🇳", // Oriya
  pa: "🇮🇳", // Punjabi
  pl: "🇵🇱", // Polaco
  ps: "🇦🇫", // Pastún
  pt: "🇵🇹", // Portugués
  qu: "🇵🇪", // Quechua
  rm: "🇨🇭", // Romanche
  ro: "🇷🇴", // Rumano
  ru: "🇷🇺", // Ruso
  rw: "🇷🇼", // Kinyarwanda
  sa: "🇮🇳", // Sánscrito
  sd: "🇮🇳", // Sindhi
  si: "🇱🇰", // Cingalés
  sk: "🇸🇰", // Eslovaco
  sl: "🇸🇮", // Esloveno
  sm: "🇼🇸", // Samoano
  sn: "🇿🇼", // Shona
  so: "🇸🇴", // Somalí
  sq: "🇦🇱", // Albanés
  sr: "🇷🇸", // Serbio
  st: "🇱🇸", // Sesotho
  su: "🇮🇩", // Sundanés
  sv: "🇸🇪", // Sueco
  sw: "🇰🇪", // Suajili
  ta: "🇮🇳", // Tamil
  te: "🇮🇳", // Telugu
  tg: "🇹🇯", // Tayiko
  th: "🇹🇭", // Tailandés
  ti: "🇪🇷", // Tigrinya
  tk: "🇹🇲", // Turcomano
  tl: "🇵🇭", // Tagalo
  tn: "🇧🇼", // Tswana
  to: "🇹🇴", // Tongano
  tr: "🇹🇷", // Turco
  ts: "🇿🇦", // Tsonga
  tt: "🇷🇺", // Tártaro
  ug: "🇨🇳", // Uigur
  uk: "🇺🇦", // Ucraniano
  ur: "🇵🇰", // Urdu
  uz: "🇺🇿", // Uzbeko
  vi: "🇻🇳", // Vietnamita
  vo: "🌐", // Volapük
  wo: "🇸🇳", // Wolof
  xh: "🇿🇦", // Xhosa
  yi: "🇮🇱", // Yidis
  yo: "🇳🇬", // Yoruba
  zh: "🇨🇳", // Chino
  zu: "🇿🇦", // Zulú
  // ... puedes extender con country-flag-emoji-json
};
